---
  - include_vars: users.yml
  - include_vars: sudofile.yml

  - name: Set includedir in sudoers
    lineinfile:
      dest: /etc/sudoers
      regexp: '^#includedir'
      line: "#includedir /etc/sudoers.d"
      state: present
      validate: "/usr/sbin/visudo -cf %s"

  - name: Create users with home directory
    user: name={{ item.username }} shell=/bin/bash createhome=yes comment='Created by Ansible'
    with_items: '{{create_users}}'

  - name: Setup | authorized key upload
    authorized_key: user={{ item.username }} key='{{ lookup('file', "files/{{ item.username }}.pub") }}'
    when: item.use_sudo == True
    with_items: '{{create_users}}'

  - name: "Sudoers | update sudoers file and validate"
    lineinfile:
      dest: "/etc/sudoers.d/{{item.username}}"
      line: "{{ item.username }} ALL=(ALL) NOPASSWD: ALL"
      regexp: '^{{ item.username }} .*'
      state: present
      create: yes
    when: item.use_sudo == True
    with_items: '{{create_users}}'

  - name: Deleting the users 
    user: name={{ item.username }} state=absent remove=yes
    with_items: '{{delete_users}}'
    ignore_errors: True


    
